version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ekb-anon-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
